# This file is automatically generated from CMake
# Include this file in CMakeLists.txt with 
# INCLUDE(${CMAKE_INSTALL_PREFIX}/share/RTQL8/RTQL8Config.cmake) 


INCLUDE_DIRECTORIES(/usr/local/include)
INCLUDE_DIRECTORIES(/usr/local/include/rtql8)
INCLUDE_DIRECTORIES(/usr/local/include/eigen-3.1.2)
SET(RTQL8_HEADERS /usr/local/include/rtql8 /usr/local/include)

LINK_DIRECTORIES(/usr/local/lib)
SET(RTQL8_LIBRARIES collision dynamics geometry integration kinematics lcpsolver optimizer renderer simulation utils yui)

